### ISSUE TITLE
Uncaught SoapFault exception: [soapenv:Server.userException] Invalid login attempt

### ISSUE THREAD

**Issue by davis3643** [netsuitephp/netsuite-php#121]
I am getting an 'InvalidSignature' error when trying to connect to my NetSuite account. This has been verified by running a Login Audit Trail Search

The role is not Administrator, and I have set up fresh Tokens and Integations etc.

Are you aware of any other issues?

**Comment by jrebs** [comment]
Not aware of this or any other issues. I know there are several people using the library actively and not having this issue. For starters, which version of the package are you running? Which version of web services are you using when you run it?

If you're running an older release or connecting with an old web services version that might explain it. If you have the issue running 2022_1, then perhaps you can provide a basic demonstration of code that triggers the issue.

**Comment by christophe-fms** [comment]
Hi,
I found that and it solves my problem, maybe the same for you :
The account ID (realm): XXXXX_SB1
The account ID in the url: XXXXX-SB1

The SB should be in upper case.

**Comment by jrebs** [comment]
Yes, your credentials do need to be correct! Glad you got it worked out. :)
