### ISSUE TITLE
Adding Filters to getPostingTransactionSummary

### ISSUE THREAD

**Issue by braedonsaunders** [netsuitephp/netsuite-php#151]
I cannot seem to get the filters added to be properly serialized into the SOAP request. Here is the function building the request:

```php
function getJobFinancials($id)
    {
        $fields = new PostingTransactionSummaryField();
        $fields->account = true;

        $customerFilterField = new RecordRef();
        $customerFilterField->internalId = $id;

        $recordRefList = new RecordRefList();
        $recordRefList->recordRef = [$customerFilterField];

        $summaryFilter = new PostingTransactionSummaryFilter();
        $summaryFilter->customer = $recordRefList;

        $summaryRequest = new GetPostingTransactionSummaryRequest();
        $summaryRequest->fields = $fields;
        $summaryRequest->filters = $summaryFilter;
        $summaryRequest->pageIndex = 1;

        $summaryResponse = $this->service->getPostingTransactionSummary($summaryRequest);

        $message = 'success';
        $status = 200;

        return response()->json([
            'message' => $message,
            'response' => $summaryResponse ?? collect()
        ], $status);
    }
```
    
When looking at the SOAP request recieved by NetSuite, the filters attribute is empty:

`<SOAP-ENV:Body>
        <ns2:getPostingTransactionSummary>
            <ns2:fields>
                <ns1:account>true</ns1:account>
            </ns2:fields>
            <ns2:filters/>
            <ns2:pageIndex>1</ns2:pageIndex>
        </ns2:getPostingTransactionSummary>
    </SOAP-ENV:Body>`
    
According to [https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N3500304.html#getPostingTransactionSummary](this) documentation, it appears this is the correct way to handle the request.

Apologies if this is something that I am doing wrong, and not a bug with netsuite-php.

**Comment by jrebs** [comment]
In your example, you are passing assigning a variable called `$fields` to the `fields` property of your `GetPostingTransactionSummaryRequest` object. This variable is not defined in your sample code. Is this the problem?

**Comment by neclimdul** [comment]
```
        $summaryFilter = new PostingTransactionSummaryFilter();
        $summaryFilter->customer = $recordRefList;
```

I suspect this is the problem. `PostingTransactionSummaryFilter` doesn't have a customer property.

```
    static $paramtypesmap = array(
        "period" => "RecordRefList",
        "account" => "RecordRefList",
        "parentItem" => "RecordRefList",
        "item" => "RecordRefList",
        "entity" => "RecordRefList",
        "department" => "RecordRefList",
        "class" => "RecordRefList",
        "location" => "RecordRefList",
        "subsidiary" => "RecordRefList",
        "book" => "RecordRefList",
    );
```

**Comment by braedonsaunders** [comment]
I see, ok that definitely makes sense as to why it is not being serialized into the request. However, according to this:

`
period | RecordRef | Filter your request by period.
account | RecordRef | Filter your request by account.
parentItem | RecordRef | Filter your request by parent item.
item | RecordRef | Filter your request by item.
customer | RecordRef | Filter your request by customer.
department | RecordRef | Filter your request by department.
class | RecordRef | Filter your request by class.
location | RecordRef | Filter your request by location.
subsidiary | RecordRef | Filter your request by subsidiary.
book | RecordRef | If you use the Multi-Book Accounting feature, filter your request by accounting book.
`

Found here: [https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N3500304.html#bridgehead_N3500569](url), it should have a customer property.

**Comment by neclimdul** [comment]
You're correct, weird...

 I wonder if there's a problem with the documentation. I suspect the correct property is `entity` which isn't in the documentation and the WSDL probably matches that which is why the serialization doesn't work.

**Comment by jrebs** [comment]
Well, the PHP Classes that NetSuite distributes for interfacing with web services do not include that property. I checked the newest download they have (2023, which I'll build into our repository soon) and it also does not have the customer property. Whether the docs or the classes are in error, I couldn't say for sure. In the past we have seen both scenarios to be true. You could modify the library code in your application to add that property in yourself and see if it works as expected, if you want to test it. If that doesn't work, then it may be that the docs are simply incorrect. Since all we have to go by are the docs and the code, it will require some experimentation.

**Comment by neclimdul** [comment]
:hand: cross-posting basically the same information :rofl:

**Comment by braedonsaunders** [comment]
Thank you for the information.

I've tried the entity property with type set to job and it is now working as intended.
