### ISSUE TITLE
AttachRequest Issue

### ISSUE THREAD

**Issue by thickey256** [netsuitephp/netsuite-php#155]
I have tried everything and making no progress, this has been driving me crazy for the past couple of days.  In short, I am trying to attach a supportCase to a salesOrder (or a salesOrder to a supportCase).

**Describe the bug**
I keep getting the 'Missing or Invalid RecordType for AttachTo' error, I *think* I need to set the type of the salesOrder to transaction as stated [here](https://stackoverflow.com/questions/50031869/how-can-i-attach-a-support-case-to-a-sales-order) (because we all trust stackoverflow!).

**How To Reproduce**
My AttachRequest looks as follows:-
```
NetSuite\Classes\AttachRequest (1) (
    public 'attachReference' -> NetSuite\Classes\AttachBasicReference (2) (
        public 'attachTo' -> NetSuite\Classes\RecordRef (4) (
            public 'name' -> null
            public 'internalId' -> integer 550846
            public 'externalId' -> null
            public 'type' -> string (10) "salesOrder"
        )
        public 'attachedRecord' -> NetSuite\Classes\RecordRef (4) (
            public 'name' -> null
            public 'internalId' -> integer 197834
            public 'externalId' -> null
            public 'type' -> string (11) "supportCase"
        )
    )
)
```

I have tried the same thing changing the SO with a file and it works fine, I tried adding the SO as a transaction but get the error
>org.xml.sax.SAXException: transaction is not a legal value for {urn:types.core_2021_1.platform.webservices.netsuite.com}RecordType

I even went as far as adding transaction to the RecordType constants with no luck.

**Expected behavior**
I would like it to attach a reference.

**Additional context**
I'm sure this is down to my ineptitude, but all the docs I have been able to find are very unclear and mostly focus on contacts which is no good to me.  I can create the relationship via the UI so I can't see it being a parent/child issue.

is this a bug or me being dumb?

**Comment by jrebs** [comment]
This doesn't look to me like a bug but like an attempt to get NetSuite web services to do something it doesn't support. The response you're getting is a pretty normal looking response when they understand what you're trying to do and are saying it's not something you can do.

Personally I've never worked with attach requests, so I can't really say whether what you're trying to do *should* be expected to work, but from a quick look at the docs, I'm not seeing that that attaching a supportCase to a transaction type record, such as a salesOrder, is supported:

https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N3481947.html#bridgehead_N3483603

That link has a few tables of the supported attachments that can be made. A salesOrder can accept file and contact attachments. A supportCase can accept file attachments. That seems to be the limit of what attachments can be made with these record types, unless I'm missing something.

**Comment by thickey256** [comment]
Thank you @jrebs, I appreciate you taking the time to look at this and respond.

However, it is possible (and even easy) do to this via the UI, they even give a guide for how to do it within the UI https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_4470989794.html#Linking-a-Transaction-to-a-Support-Case.

The web service docs seem very file and contact focused.  On the page you provided it says:
`The following table lists all records that support the attach/detach operations. It **also** lists which records can accept file attachments as well as which records can accept Contact records as attachments.`
Perhaps I am just reading it hoping what I want to achieve is possible, but I interpret that sentence to mean "You can attach records to all the items in this list ALSO if you want to attach a contact or file then it can be done on the following ways". 

But I could be way wrong, but it seems like an odd thing to exclude.

**Comment by neclimdul** [comment]
Not much to add since I also don't have any experience here. Since this library is basically mostly data objects directly from Oracle, as jrebs pointed out these sort of things generally aren't "bugs" so much as an exercise in getting the right things lined up.

As far are your type error on the transaction, you can generally avoid these by using the [RecordType](https://github.com/netsuitephp/netsuite-php/blob/master/src/Classes/RecordType.php) constants like RecordType::customTransaction. That'll generally help avoid typos and get the correct enumerated value.

**Comment by thickey256** [comment]
I downloaded and tried the same thing using the PHP toolkit from NetSuite (and I feel dirty for doing it).

This has the same response so, I'm going to close this as it's not a bug with this library.  I may have to give it a shot with suitescripts instead. ¯\_(ツ)_/¯
