### ISSUE TITLE
NetSuite\Logger::getSoapCallResponseMessage(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by alex-volga** [netsuitephp/netsuite-php#156]
**Describe the bug**
v2023.1.0
Error message:

> NetSuite\Logger::getSoapCallResponseMessage(): Return value must be of type string, null returned

Line 86

**Expected behavior**
Return type can be null.

https://www.php.net/manual/en/soapclient.getlastresponse.php
`public SoapClient::__getLastResponse(): ?string`

**Comment by jrebs** [comment]
Thanks. Since the package already has a require on php >= 7.1, we can just make the return nullable on getSoapCallResponseMessage(). I'll try to get that changed and released tonight.
