### ISSUE TITLE
psr/log version scope too narrow.

### ISSUE THREAD

**Issue by chumanfu** [netsuitephp/netsuite-php#159]
Currently the version of `psr/log` is ^1.0. This means if you application has a dependency on `psr/log` > 1.0 you are unable to upgrade to the latest version.

**Comment by lucashodge** [comment]
I am using this on a Drupal project an I can't upgrade to Drupal 10 because it uses symphony 6 and this has psr/log (~3.0.0).

**Comment by chumanfu** [comment]
> Please review the pull request then. There's an outstanding question.

Done

**Comment by jrebs** [comment]
Closed by #154
