### ISSUE TITLE
Issue with Item Fufillment creation, and commit quantities (only with inventoryLocation)

### ISSUE THREAD

**Issue by benjy8001** [netsuitephp/netsuite-php#170]
### Discussed in https://github.com/netsuitephp/netsuite-php/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **benjy8001** May 28, 2024</sup>
Hi !

Actually i create an Item Fufillment from a Sales Order (with an intialize request and a create request), but each line items have no inventory location set.

When i try to create an item fulfillment from a sales order including items with inventory location, it leads to this message :

`App\Exceptions\Netsuite\ItemFulfillmentCreationException  Unable to create Item Fulfillment from Sale Order 5278060
You must have at least one valid line item for this transaction.`

My goal is to : 
1/ Create an item fulfillment linked to a Sales order
2/ Commit quantities in the location in order to have an up to date inventory.

Maybe the `ItemFulfillmentItem` class is missing the `inventoryLocation` properties ?

Thanks for your help !</div>

**Comment by jrebs** [comment]
There's no indication this is a bug with the package. If you believe it is, please open a new ticket and follow the template that is provided. The discussion already opened is the correct place to ask about this.
