### ISSUE TITLE
Token Based Authentication

### ISSUE THREAD

**Issue by stevenbrookes** [netsuitephp/netsuite-php#171]
I'm attempting to use TBA with endpoint 2021_1 as per the example in the documentation.  I'm getting the error 

```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>soapenv:Server.userException</faultcode>
            <faultstring>The request could not be understood by the server due to malformed syntax.</faultstring>
            <detail>
                <platformFaults:invalidCredentialsFault
                        xmlns:platformFaults="urn:faults_2021_1.platform.webservices.netsuite.com">
                    <platformFaults:code>USER_ERROR</platformFaults:code>
                    <platformFaults:message>The request could not be understood by the server due to malformed syntax.
                    </platformFaults:message>
                </platformFaults:invalidCredentialsFault>
                <ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">partners133.prod-lhr-eu4.core.ns.internal
                </ns1:hostname>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>

```
The request that the library is sending is.  All the keys etc replaced with **** for the moment.

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
                   xmlns:ns1="urn:messages_2021_1.platform.webservices.netsuite.com" xmlns:ns2="ns">
    <SOAP-ENV:Header>
        <ns2:tokenPassport>
            <account>****</account>
            <consumerKey>****</consumerKey>
            <token>****</token>
            <nonce>****</nonce>
            <timestamp>****</timestamp>
            <signature>
                <_>****=</_>
                <algorithm>HMAC_SHA256</algorithm>
            </signature>
        </ns2:tokenPassport>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <ns1:getAll>
            <ns1:record recordType="currency"/>
        </ns1:getAll>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

```
I tried the same request in Postman and found that the issue seems to be the signature section.  If I replace 

 ```
          <signature>
                <_>****</_>
                <algorithm>HMAC_SHA256</algorithm>
            </signature>
```

with 

`<signature algorithm='HMAC_SHA256'>****</signature>
`

then it returns the list of currencies correctly.  

Now I'm running on PHP 8.3 so I'm thinking this may be some internal PHP XML handling issue.  Any thoughts on this?  I'll do some research to see if something has changed in PHP or if it's possible to override the behaviour.

**Comment by neclimdul** [comment]
that's very strange. even if the weird `_` handling broke in 8.3, the signature shouldn't move like that. almost like something broke with the WSDL or something.

What version of the library are you using?

**Comment by stevenbrookes** [comment]
Hi, so I'm using the latest dev-master as I need the psr-log support recently added.  So effectively 2023_2.  I loaded the WSDL into SoapUI and it does show the correct form of the tokenPassport section to be as follows.

      <urn:tokenPassport>
         <urn1:account>?</urn1:account>
         <urn1:consumerKey>?</urn1:consumerKey>
         <urn1:token>?</urn1:token>
         <urn1:nonce>?</urn1:nonce>
         <urn1:timestamp>?</urn1:timestamp>
         <urn1:signature algorithm="?">?</urn1:signature>
      </urn:tokenPassport>

Still not clear why the previous _ handling doesn't work - that seems to be undocumented behaviour of the PHP SoapClient extension.  There seems to have been quite a lot of activity in that extension of late so perhaps that broke the behaviour.  It does seem safer to use a SoapVar though as at least that's straightforward to use.  No real documentation on that function either though ;)

Are you happy to accept my merge request?

**Comment by neclimdul** [comment]
Good to know things are working now. I wonder if there was some sort of WSDL cache problem or something.

As far as I know, `_` is the correct way to do this which you'll find through out the comments and internet as well as the source of the soap extension.

Since that's the case and the current code is basically an exact copy of the sample code from Oracle I'm inclined to keep it the way it is unless one of the other maintainers disagrees.

**Comment by stevenbrookes** [comment]
So I did a bit more digging.  We were using the option to inject our own SoapClient as this provided logging.  For some reason this client was behaving differently to the native one created by the library.  Since the library now provides logging natively we've switched to using that and now it connects up fine with no need to change the authentication. 

Thanks for the input above as it helped push me to investigate further,  And for the lib of course!

**Comment by jrebs** [comment]
I didn't sound in on this yet because I wanted to have some clear time to sit down and do some testing of my own, as it didn't quite add up to me that this would just not work suddenly. Thanks for sticking with it and posting the explanation.
