### ISSUE TITLE
Soap error

### ISSUE THREAD

**Issue by aadityamundhalia** [netsuitephp/netsuite-php#32]
SoapFault  : SOAP-ERROR: Parsing WSDL: Couldn't load from '/wsdl/v_0/netsuite.wsdl' : failed to load external entity "/wsdl/v_0/netsuite.wsdl"

  at /var/www/html/beechwood-api/vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.php:50
    46|     {
    47|         $this->config = $config;
    48|         $options = $this->createOptions($this->config, $options);
    49|         $wsdl = $this->createWsdl($this->config);
  > 50|         $this->client = $client ?: new SoapClient($wsdl, $options);
    51|     }
    52|
    53|     public static function createFromEnv($options = array(), $client = null)
    54|     {

  Exception trace:

  1   SoapClient::SoapClient("/wsdl/v_0/netsuite.wsdl")
      /var/www/html/beechwood-api/vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.php:50

  2   NetSuite\NetSuiteClient::__construct()
      /var/www/html/beechwood-api/app/Console/Commands/CustomerCommand.php:102

  Please use the argument -v to see more details.

**Comment by sonjaq** [comment]
@aadityamundhalia It appears you don't have a `$config['endpoint']` value correctly set for the Netsuite endpoint. It's hitting `/wsdl/v_0/netsuite.wsdl` - normally that should have a value, like `/wsdl/v_2016_2_0/netsuite.wsdl`. These steps are in the first code block on the README.

**Comment by aadityamundhalia** [comment]
It works fine but as soon as I clear cache it do not recognize wsdl. Any think I can do abot that.

**Comment by jrebs** [comment]
Not sure exactly the details surrounding your caching system, but @sonjaq appears to be correct and the issue seems to be with the contents of your $config array being passed in.
