### ISSUE TITLE
Customer number format

### ISSUE THREAD

**Issue by Richi2293** [netsuitephp/netsuite-php#82]
Hi,
how can i change the formatting of the customer number? The kind that I don't want it and just plain text consisting of numbers is fine.

I also tried to assign null value to the formatting field but it is not working

**Comment by jrebs** [comment]
Sorry, I don't understand what you're asking for. Customer numbers are just numbers. That's what you get in the Customer objects. For my integration purposes, I tend to work with `internalId` values, primarily.

**Comment by Richi2293** [comment]
Hi,

I solved it by inserting it in the mobilePhone field and not in the phone field as I was doing.
It seems that if I insert the mobile number in the phone field it automatically makes me its standard formatting instead in the mobilePhone field it does nothing and takes the number that is entered

**Comment by jrebs** [comment]
Okay...nowhere in your message did you mention 'phone' number. The 'customer number' is a rather different thing. :)
