### ISSUE TITLE
Example of a edit action

### ISSUE THREAD

**Issue by Richi2293** [netsuitephp/netsuite-php#89]
Hi,

I need to figure out how to do an edit action and I see that in the readme it is not present.
Possible to have an example?
For example I need to edit an ItemFulFillment record.

Thanks

**Comment by jrebs** [comment]
I'm not sure I've ever edited an item fulfillment, as my integration just creates/reads them. In theory I don't see why this wouldn't be like any other record update. You take your record object, modify fields as needed, then use an UpdateRequest to send it to web services.

```php
// manipulate your $itemFulfillment as desired
$request = new NetSuite\Classes\UpdateRequest();
$request->record = $itemFulfillment;
$response = $client->update($request);
```

I do know that there are a bunch of fields on item fulfillments that are read-only and you'll run into errors trying to set them through web services. I recommend using the NetSuite Schema Browser to get information about the various classes and properties, their types, limitations and other notes.
